rm ./frameworks/av/camera/tests/Android.mk
rm ./frameworks/av/media/libstagefright/foundation/tests/Android.mk
rm ./frameworks/av/media/libstagefright/codec2/tests/Android.mk
rm ./frameworks/av/media/libaudioprocessing/tests/Android.mk
rm ./frameworks/av/media/libmediaplayerservice/tests/Android.mk
rm ./frameworks/av/media/libaaudio/tests/Android.mk
rm ./frameworks/av/services/camera/libcameraservice/tests/Android.mk
rm ./frameworks/av/services/mediadrm/tests/Android.mk
rm ./frameworks/native/opengl/tests/Android.mk
rm ./frameworks/native/services/sensorservice/tests/Android.mk
rm ./frameworks/native/services/surfaceflinger/tests/Android.mk
rm ./frameworks/base/libs/androidfw/tests/Android.mk
rm ./frameworks/base/wifi/tests/Android.mk
rm ./frameworks/base/packages/Osu2/tests/Android.mk
rm ./frameworks/base/packages/SettingsLib/tests/Android.mk
rm ./frameworks/base/packages/WAPPushManager/tests/Android.mk
rm ./frameworks/base/packages/CarrierDefaultApp/tests/Android.mk
rm ./frameworks/base/packages/ExtServices/tests/Android.mk
rm ./frameworks/base/packages/SystemUI/tests/Android.mk
rm ./frameworks/base/packages/PrintSpooler/tests/Android.mk
rm ./frameworks/base/packages/MtpDocumentsProvider/tests/Android.mk
rm ./frameworks/base/test-runner/tests/Android.mk
rm ./frameworks/base/media/mca/tests/Android.mk
rm ./frameworks/base/tests/testables/tests/Android.mk
rm ./frameworks/base/tests/ImfTest/tests/Android.mk
rm ./frameworks/base/tests/Camera2Tests/CameraToo/tests/Android.mk
rm ./frameworks/base/tests/Camera2Tests/SmartCamera/SimpleCamera/tests/Android.mk
rm ./frameworks/base/tests/SmokeTest/tests/Android.mk
rm ./frameworks/base/services/tests/Android.mk
rm ./frameworks/base/lowpan/tests/Android.mk
rm ./frameworks/base/nfc-extras/tests/Android.mk
rm ./frameworks/opt/telephony/tests/Android.mk
rm ./frameworks/opt/chips/tests/Android.mk
rm ./frameworks/opt/vcard/tests/Android.mk
rm ./frameworks/opt/calendar/tests/Android.mk
rm ./frameworks/opt/net/wifi/tests/Android.mk
rm ./frameworks/opt/net/ims/tests/Android.mk
rm ./frameworks/opt/net/lowpan/libandroid_net_lowpan/tests/Android.mk
rm ./frameworks/layoutlib/bridge/tests/Android.mk
rm ./frameworks/layoutlib/create/tests/Android.mk
rm ./frameworks/rs/rsov/tests/Android.mk
rm ./frameworks/rs/tests/Android.mk
rm ./frameworks/ex/common/tests/Android.mk
rm ./frameworks/ex/camera2/portability/tests/Android.mk
rm ./frameworks/ex/camera2/utils/tests/Android.mk
rm ./packages/inputmethods/LatinIME/tests/Android.mk
rm ./packages/apps/Email/tests/Android.mk
rm ./packages/apps/Launcher2/tests/Android.mk
rm ./packages/apps/Contacts/tests/Android.mk
rm ./packages/apps/Music/tests/Android.mk
rm ./packages/apps/CarrierConfig/tests/Android.mk
rm ./packages/apps/Messaging/tests/Android.mk
rm ./packages/apps/Camera2/tests/Android.mk
rm ./packages/apps/Car/Settings/tests/Android.mk
rm ./packages/apps/Car/Messenger/tests/Android.mk
rm ./packages/apps/Settings/tests/Android.mk
rm ./packages/apps/Launcher3/tests/Android.mk
rm ./packages/apps/EmergencyInfo/tests/Android.mk
rm ./packages/apps/QuickSearchBox/tests/Android.mk
rm ./packages/apps/DocumentsUI/tests/Android.mk
rm ./packages/apps/Gallery/tests/Android.mk
rm ./packages/apps/Nfc/tests/Android.mk
rm ./packages/apps/CellBroadcastReceiver/tests/Android.mk
rm ./packages/apps/TV/tests/Android.mk
rm ./packages/apps/KeyChain/tests/Android.mk
rm ./packages/apps/ManagedProvisioning/tests/Android.mk
rm ./packages/apps/UnifiedEmail/tests/Android.mk
rm ./packages/apps/StorageManager/tests/Android.mk
rm ./packages/apps/PackageInstaller/tests/Android.mk
rm ./packages/apps/BasicSmsReceiver/tests/Android.mk
rm ./packages/apps/Calendar/tests/Android.mk
rm ./packages/apps/Bluetooth/tests/Android.mk
rm ./packages/apps/LegacyCamera/tests/Android.mk
rm ./packages/providers/TelephonyProvider/tests/Android.mk
rm ./packages/providers/CallLogProvider/tests/Android.mk
rm ./packages/providers/CalendarProvider/tests/Android.mk
rm ./packages/providers/ContactsProvider/tests/Android.mk
rm ./packages/providers/DownloadProvider/tests/Android.mk
rm ./packages/providers/PartnerBookmarksProvider/tests/Android.mk
rm ./packages/providers/BlockedNumberProvider/tests/Android.mk
rm ./packages/providers/TvProvider/tests/Android.mk
rm ./packages/services/Telecomm/tests/Android.mk
rm ./packages/services/Car/tests/Android.mk
rm ./packages/services/Telephony/tests/Android.mk
rm ./vendor/mediatek/proprietary/frameworks/opt/tatfcommon/tests/Android.mk
rm ./vendor/mediatek/proprietary/frameworks/opt/mage/legacy/ngin3d/tests/Android.mk
rm ./vendor/mediatek/proprietary/frameworks/ex/chips/tests/Android.mk
rm ./vendor/mediatek/proprietary/operator/packages/apps/Launcher3/tests/Android.mk
rm ./vendor/mediatek/proprietary/operator/packages/apps/RCSe/Common/RcsApp/tests/Android.mk
rm ./vendor/mediatek/proprietary/operator/packages/apps/NoteBook/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/apps/EngineerMode/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/apps/SettingsLib/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/apps/CarrierConfig/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/apps/Bypass/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/apps/Omacp/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/apps/MTKLogger/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/apps/VoiceCommand/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/apps/Launcher3/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/apps/EmergencyInfo/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/apps/DocumentsUI/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/apps/YGPS/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/apps/PrivacyProtectionLock/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/apps/CellBroadcastReceiver/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/apps/MtkSettings/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/apps/MTKAndroidSuiteDaemon/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/apps/FileManager/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/apps/Bluetooth/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/apps/CalendarImporter/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/providers/ContactsProvider/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/providers/DownloadProvider/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/providers/ApplicationsProvider/tests/Android.mk
rm ./vendor/mediatek/proprietary/packages/services/Telecomm/tests/Android.mk
rm ./vendor/mediatek/proprietary/hardware/libgem/lib/gui_debug/tests/Android.mk
rm ./vendor/mediatek/proprietary/hardware/ril/rilproxy/tests/Android.mk
rm ./vendor/mediatek/proprietary/hardware/ril/rilproxy/mtk-rilproxy/telephony/agps/tests/Android.mk
rm ./vendor/mediatek/proprietary/hardware/ril/fusion/tests/Android.mk
rm ./vendor/mediatek/proprietary/hardware/mtkcam/feature/hdr/2.0/tests/Android.mk
rm ./vendor/mediatek/proprietary/hardware/mtkcam/feature/hdr/2.3/tests/Android.mk
rm ./vendor/mediatek/proprietary/hardware/mtkcam/feature/hdr/1.0/tests/Android.mk
rm ./vendor/mediatek/proprietary/hardware/mtkcam/feature/common/autorama/tests/Android.mk
rm ./vendor/mediatek/proprietary/hardware/mtkcam/feature/iris/1.0/tests/Android.mk
rm ./vendor/mediatek/proprietary/hardware/c2kril/tests/Android.mk
rm ./vendor/mediatek/proprietary/trustzone/microtrust/source/common/270/ut_gatekeeper/tests/Android.mk
